### ISSUE TITLE
Crash when changing server

### ISSUE THREAD

**Issue by LaughNgamez** [leigholiver/OBS-SC2Switcher#10]
When changing server in game OBS Studio seems to crash.

https://obsproject.com/logs/KAFEa6ooTTD15po5

**Comment by leigholiver** [comment]
Hi my apologies for the bug. Which version are you using? I can't seem to reproduce it. Are you able to get it to crash every time? I have tried using the globe button in the menu and logging out/back in.

**Comment by LaughNgamez** [comment]
Hello, thanks for getting back to me!

I'm running the latest release .94 but it happened before that if I recall correctly. The error happens 100% of the time I use the globe button. It appears it also happens when logging in too so it makes me think it has to do with the login screen and not swapping regions.

Great plugin btw and hoping this can be resolved!

**Comment by leigholiver** [comment]
Thanks for the extra info. I should have some time to look into this today so I'll keep you updated.

Which scene switches are you using? This might help me to reproduce it.

**Comment by LaughNgamez** [comment]
![image](https://user-images.githubusercontent.com/12781929/48233240-557b1100-e369-11e8-9fed-f542f96236f4.png)

**Comment by LaughNgamez** [comment]
I also get an odd bug. Under the Usernames it spams one users name, I press delete then it goes away. It periodically comes back despite me not having it enabled.

How does one fully reset the Usernames? I'm not sure where the data is stored.

**Comment by 2press** [comment]
> 
> 
> I also get an odd bug. Under the Usernames it spams one users name, I press delete then it goes away. It periodically comes back despite me not having it enabled.
> 
> How does one fully reset the Usernames? I'm not sure where the data is stored.

That's an issue I have already reported in https://github.com/leigholiver/OBS-SC2Switcher/issues/8 - I thought that it was fixed. Maybe it's not.

And I can't reproduce the login crash of OBS either. I just had OBS crash once when starting up SC2, but I fail at reproducing it.

**Comment by leigholiver** [comment]
The configuration is stored with the OBS settings, in C:/Users/[your username]/AppData/Roaming/obs-studio/basic/scenes/[your obs profile name].json

If you're comfortable editing json you can just open this file, ctrl+f for "sc2switcher2" and remove the entries from the usernames section. I'll make sure in the next update that there is a way to completely reset the settings. I'm starting to wonder if there is an issue with them as I've still not yet been able to reproduce either of these issues, but I have been able to get the duplicates to happen in the web url box so this might lead me onto the right track. 

LaughNgamez - does this still happen on a fresh obs configuration? if you would be happy to do a test, you could check this by closing obs and temporarily moving your C:/Users/[your username]/AppData/Roaming/obs-studio/basic/scenes/[your obs profile name].json file (and the .bak file with the same name) out of that folder. When you start obs you should have a fresh configuration you can use to see if it still crashes. You can restore your settings after the test by closing obs, moving the files back, and restarting obs.

Thanks for your patience with this

**Comment by leigholiver** [comment]
Just released an update with an option to reset the settings along with a bunch of bug fixes. 
Do either of you use the Scene Collections feature in obs? That seemed to be the biggest culprit of duplicates happening and is now fixed.

**Comment by LaughNgamez** [comment]
I did use fresh scenes/profiles and it still happened. It seems however upon updating & replacing the plugin the issue is fixed!

**Comment by leigholiver** [comment]
Great news :) thanks to you both for your help

**Comment by LaughNgamez** [comment]
Apparently it's not fixed... just happened again. When I said it was fixed I only tested it once, trying to stream today it crashed on launch.

**Comment by LaughNgamez** [comment]
@leigholiver 

Actually had a crash today while streaming not logging in out. Pretty sure it happened when loading into game.

https://obsproject.com/logs/0kSVXXvEQEVwnKKL

**Comment by leigholiver** [comment]
Thanks for the report, I'll try to take another look into this today. I'm really sorry about the instability

**Comment by 2press** [comment]
This crash occurred to me today as well and happened when OBS was already open and the switcher active while starting SC2 at the initial automatic login process.

**Comment by leigholiver** [comment]
I'm currently trying to figure this one out but sadly I'm still unable to reproduce it, just wondering if you guys had any tips to point me in the right direction? 
This is the process im going through:
I'm starting from a fresh obs profile, adding two scenes, setting one scene to out of game and the other to ingame/replay/obs, turning on the scene switcher and starting it, then opening SC2, entering a game, leaving a game, logging out, logging in again, entering a game, leaving the game, switching region using the globe menu. 
Are you using any scene collections/profiles/transitions or anything outside of the above that I need to take into account?

**Comment by LaughNgamez** [comment]
I believe I have a slight delay on scene transitions but will have more of
a look when I get home.

**Comment by 2press** [comment]
It seems that this issue is not entirely empirical - I can't reproduce it most of time (happened twice so far). My guess would be that it might be caused by a query to the SC2 client API precisely at a certain (invalid) state of SC2 that is only present for short duration during the login/start up process. If that is the case, you could increase the probability to reproduce this bug by increasing the request rate of the client API. Do you catch all possible errors that could occur in your curl requests?

Could you increase the logging so we can help to pinpoint you towards the error via the log file as you seem unable to reproduce it while LaughNgamez seems rather good at this task?

**Comment by leigholiver** [comment]
Hi guys, I've put together a test version with a lot of extra logging. It uses the obs log which is located in C:\Users\[your username]\AppData\Roaming\obs-studio\logs\[date and time].txt 
If you could give it a try and let me know how it goes I'd really appreciate it - I've narrowed it down to a couple of potential places so the logs should give me enough info to fix it. 

Thanks again for all your patience with this.

[sc2switcher.dll.zip](https://github.com/leigholiver/OBS-SC2Switcher/files/2591801/sc2switcher.dll.zip)

**Comment by 2press** [comment]
Installed the test version, started OBS studio, started SC2 and OBS crashed during the login screen. This is the log file:

[2018-11-17 14-49-36.txt](https://github.com/leigholiver/OBS-SC2Switcher/files/2591856/2018-11-17.14-49-36.txt)
[Crash 2018-11-17 14-50-14.txt](https://github.com/leigholiver/OBS-SC2Switcher/files/2591863/Crash.2018-11-17.14-50-14.txt)


Unfortunately, It seems like the error isn't logged.

**Comment by leigholiver** [comment]
Thanks for the quick reply - That's correct but I can tell from the last message logged where the crash is happening. Looking into it now.

**Comment by leigholiver** [comment]
[sc2switcher.zip](https://github.com/leigholiver/OBS-SC2Switcher/files/2591907/sc2switcher.zip)

Update.

**Comment by 2press** [comment]
It crashes again with the updated version:

[2018-11-17 18-04-23.txt](https://github.com/leigholiver/OBS-SC2Switcher/files/2592042/2018-11-17.18-04-23.txt)
[Crash 2018-11-17 18-05-09.txt](https://github.com/leigholiver/OBS-SC2Switcher/files/2592043/Crash.2018-11-17.18-05-09.txt)

P.S.: Before starting SC2 I have switched manually to the "Out of Game" scene that the switcher should initially switch to.

**Comment by leigholiver** [comment]
Hopefully this one is a little closer. Thanks for your help testing these.
[sc2switcher.zip](https://github.com/leigholiver/OBS-SC2Switcher/files/2592382/sc2switcher.zip)

**Comment by LaughNgamez** [comment]
Ok interestingly enough this happens with one of my scene collections but apparently not with one of my others.

Any guesses as to which element it could be related to?

**Comment by leigholiver** [comment]
Each scene collection should have its own configuration for the plugin so it may be that its not started/scene switcher isnt enabled/the scenes arent set up?
You could try setting up two blank scenes and seeing if it still crashes. If it doesn't you could try enabling one at a time and seeing which scene is causing the crash. 

If you've tried one of the test versions we've been trying could you post a log? I'd be interested to see if its crashing in the same place as 2press has been experiencing.

**Comment by LaughNgamez** [comment]
[2018-11-17 15-47-53.txt](https://github.com/leigholiver/OBS-SC2Switcher/files/2592400/2018-11-17.15-47-53.txt)
[2018-11-17 15-45-35.txt](https://github.com/leigholiver/OBS-SC2Switcher/files/2592401/2018-11-17.15-45-35.txt)

**Comment by leigholiver** [comment]
Thanks - I think I've got it now. Based on your logs it looks like I had it last time but missed another spot where I made the same error. 
[sc2switcher.zip](https://github.com/leigholiver/OBS-SC2Switcher/files/2592419/sc2switcher.zip)

**Comment by LaughNgamez** [comment]
Seems fixed! If it happens again I'll let you know. Once again thanks for the great support & great plugin!

**Comment by leigholiver** [comment]
Great news, I'll keep my fingers crossed! Thanks for your patience with it
